### PR TITLE
NOJIRA: descriptions for core repositories

### PR DESCRIPTION
**Pull request by cstrobbe**

### CODE REVIEW

**Comment by sgithens** [comment]
Thanks @cstrobbe hope to get a bit of time to spend on the website this weekend to merge these in, I also need to add a bunch of lines for other new repos that we've created.

**Comment by cstrobbe** [comment]
Do you also plan to list repositories that are hosted outside GPII? I'm thinking of the following: 
- [Statistical Matchmaker: Analysis Component](https://github.com/REMEXLabs/GPII-Statistical-Matchmaker-Analysis/)
- [Statistical Matchmaker: Training Data](https://github.com/REMEXLabs/GPII-Statistical-Matchmaker-Data) (used by the Analysis Component to create input for the Runtime Component)
- [Statistical Matchmaker: Runtime Component](https://github.com/REMEXLabs/GPII-Statistical-Matchmaker) (the component that gets deployed in order to process matchmaking requests)
- [Rule-based Matchmaker](https://github.com/NickKaklanis/RuleBased_MatchMaker)
- [RESTful web-service of the CLOUD4All Rule-based MatchMaker](https://github.com/NickKaklanis/RuleBasedMatchMaker_RESTful_WS_Maven)
- [Cloud4Chrome](https://github.com/GutiX/chrome4cloud/)
- [Service Synthesizer Tool (SST)](https://github.com/NickKaklanis/ServiceSynthesizerTool_RESTful_WS_Maven) (not sure whether this is all you need or just the Web Service)
- Semantic Alignment Tool (SAT): apparently not hosted on GitHub?

**Comment by colinbdclark** [comment]
We most definitely need to add the repositories that are hosted in separate Github organizations. I'm hoping someone can create a child page of the main gpii.github.io site specifically for Cloud4All, which lists all of the components for the project, including these you list and others, Christophe (such as the SST, SAT, etc).

Any volunteers?

**Comment by cstrobbe** [comment]
This would be another HTML page in the same directory, right? What name would you like this to have? I think I can work on this later this week.

**Comment by colinbdclark** [comment]
Wow, thanks! Yes, just another file in the same directory. Perhaps cloud4all.html is a good name.

Thanks again for offering. It is hugely appreciated.

**Comment by kaspermarkus** [comment]
+1

**Comment by cstrobbe** [comment]
The changes are now in their own branch (instead of a bit of online editing that resulted in patch-1): https://github.com/GPII/gpii.github.io/pull/2.

**Comment by cstrobbe** [comment]
I'm closing this pull request because of the "newer" one at https://github.com/GPII/gpii.github.io/pull/2.

**Pull request closed without merging**
